export 'items_list_card.dart';
export 'client.dart';
export 'address.dart';
export 'name.dart';
export 'phone.dart';
export 'email.dart';
export 'status.dart';
export 'platform.dart';
export 'deliverer.dart';